global using Grpc.Core;
global using Grpc.Net.Client;
global using Identity.Client.Cache;
global using Identity.Client.Enums;
global using Identity.Client.Extensions;
global using Identity.Client.Models;
global using Identity.Client.Rules;
global using Identity.Server.Grpc.Protos;
global using Microsoft.Extensions.Configuration;
