global using Identity.Context;
global using Identity.Entity.Application;
global using Identity.Entity.Page;
global using Identity.Entity.User;
global using Identity.Service.Rules;
global using Identity.Service.Services;
global using Identity.Services.Base;
global using Identity.ViewModels.Account;
global using Identity.ViewModels.Account.Response;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using static Identity.ViewModels.Api.ApiResponse;